# -*- coding: utf-8 -*-
"""Untitled59.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Df8d7kRJEJi4ZlMM5xLqHx9e4gAjcTTI
"""

import streamlit as st
import pandas as pd
import joblib
import sklearn

# Set Page Config
st.set_page_config(page_title="Alcohol Consumption Predictor", page_icon="🍷")

# 1. Load the Model
@st.cache_resource
def load_model():
    # Make sure this filename matches your file exactly
    return joblib.load('trained_model (1).joblib')

st.title("📊 Alcohol Consumption Predictor")
st.write("Predicting **Total Pure Alcohol Consumption** based on servings.")

# Try to load the model
try:
    model = load_model()
    st.sidebar.success(f"✅ Model Loaded (sklearn {sklearn.__version__})")
except AttributeError:
    st.error("### ❌ Version Mismatch Error")
    st.info("The model requires **scikit-learn 1.6.1**. Please ensure your `requirements.txt` has `scikit-learn==1.6.1` and reboot your Streamlit app.")
    st.stop()
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

# 2. Comprehensive Country List (extracted from your model)
countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Azerbaijan',
    'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belize', 'Bolivia', 'Bosnia', 'Botswana', 'Brazil',
    'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cameroon', 'Canada', 'Central African Republic',
    'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Cote', 'Croatia',
    'Cuba', 'Cyprus', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
    'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'France', 'Gabon', 'Gambia', 'Georgia',
    'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'India', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
    'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
    'Lesotho', 'Liberia', 'Libya', 'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
    'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Myanmar',
    'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Korea',
    'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
    'Portugal', 'Romania', 'Russian Federation', 'San Marino', 'Sao Tome & Principe', 'Saudi Arabia', 'Senegal',
    'Serbia', 'Sierra Leone', 'Slovenia', 'Solomon Islands', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan',
    'Suriname', 'Swaziland', 'Sweden', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad & Tobago',
    'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
    'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
]

# 3. User Inputs
st.subheader("Input Parameters")
col1, col2 = st.columns(2)

with col1:
    selected_country = st.selectbox("Country", sorted(countries))
    beer = st.number_input("Beer Servings", min_value=0, max_value=1000, value=100)

with col2:
    spirit = st.number_input("Spirit Servings", min_value=0, max_value=1000, value=50)
    wine = st.number_input("Wine Servings", min_value=0, max_value=1000, value=25)

# 4. Prediction Logic
if st.button("Calculate Prediction"):
    # Must match training feature names exactly
    input_df = pd.DataFrame({
        'country': [selected_country],
        'beer_servings': [beer],
        'spirit_servings': [spirit],
        'wine_servings': [wine]
    })

    try:
        prediction = model.predict(input_df)
        st.divider()
        st.subheader("Results")
        st.metric(label="Total Pure Alcohol Consumption (Litres)", value=f"{prediction[0]:.2f}")
    except Exception as e:
        st.error(f"Prediction failed. This usually happens if the input columns don't match the model training. Error: {e}")