# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKGiWCs9LRzMYWBAUQfIp49UMJhS5cvN
"""

import streamlit as st
import pandas as pd
import joblib
import sklearn

# Set page title
st.set_page_config(page_title="Alcohol Consumption Predictor")

# 1. Load the Model with Version Check
@st.cache_resource
def load_model():
    return joblib.load('trained_model (1).joblib')

st.title("📊 Alcohol Consumption Predictor")

try:
    model = load_model()
    st.sidebar.success(f"Model loaded (sklearn {sklearn.__version__})")
except AttributeError as e:
    st.error("### ⚠️ Version Mismatch Error")
    st.write(f"The model was built with sklearn 1.6.1, but the current environment is different.")
    st.info("Ensure your **requirements.txt** contains: `scikit-learn==1.6.1` and restart the app.")
    st.stop()

# 2. Define Country List (Heuristic based on model data)
countries = ["USA", "United Kingdom", "France", "Germany", "Canada", "Australia", "India", "Brazil", "South Africa"] # Add more as per your dataset

# 3. User Input Interface
st.subheader("Enter Consumption Details")
col1, col2 = st.columns(2)

with col1:
    country = st.selectbox("Select Country", sorted(countries))
    beer = st.number_input("Beer Servings", min_value=0, value=100)

with col2:
    spirit = st.number_input("Spirit Servings", min_value=0, value=50)
    wine = st.number_input("Wine Servings", min_value=0, value=25)

# 4. Prediction Logic
if st.button("Predict Total Pure Alcohol"):
    # The dataframe columns must match the training features exactly
    input_df = pd.DataFrame({
        'country': [country],
        'beer_servings': [beer],
        'spirit_servings': [spirit],
        'wine_servings': [wine]
    })

    prediction = model.predict(input_df)

    st.divider()
    st.metric(label="Predicted Total Pure Alcohol (Litres)", value=f"{prediction[0]:.2f}")