# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4Nb7vonEwuSlHu6qJ71E8-lglcfQV9j
"""

import streamlit as st
import pandas as pd
import joblib

# Set Page Configuration
st.set_page_config(page_title="Alcohol Consumption Predictor", layout="centered")

# Load the trained model
@st.cache_resource
def load_model():
    # Ensure the filename matches your uploaded file exactly
    return joblib.load('trained_model (1).joblib')

try:
    model = load_model()
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.info("Tip: Ensure your scikit-learn version matches the one used to create the model (v1.6.1).")

# App Header
st.title("📊 Alcohol Consumption Predictor")
st.write("Predict the **Total Pure Alcohol Consumption** per person based on servings.")

# Define the list of countries (extracted from your model metadata)
countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua & Barbuda", "Argentina", "Armenia",
    "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus",
    "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia-Herzegovina", "Botswana", "Brazil",
    "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cote d'Ivoire", "Cabo Verde", "Cambodia",
    "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia",
    "Comoros", "Congo", "Cook Islands", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
    "DR Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
    "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland",
    "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India",
    "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan",
    "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon",
    "Lesotho", "Liberia", "Libya", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia",
    "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
    "Micronesia", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "Niue", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea",
    "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "South Korea", "Moldova",
    "Romania", "Russian Federation", "Rwanda", "St. Kitts & Nevis", "St. Lucia",
    "St. Vincent & the Grenadines", "Samoa", "San Marino", "Sao Tome & Principe", "Saudi Arabia",
    "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
    "Solomon Islands", "Somalia", "South Africa", "Spain", "Sri Lanka", "Sudan", "Suriname",
    "Swaziland", "Sweden", "Switzerland", "Syria", "Tajikistan", "Thailand", "Macedonia",
    "Timor-Leste", "Togo", "Tonga", "Trinidad & Tobago", "Tunisia", "Turkey", "Turkmenistan",
    "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Tanzania", "USA",
    "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
]

# Layout for inputs
col1, col2 = st.columns(2)

with col1:
    country_input = st.selectbox("Select Country", sorted(countries))
    beer_input = st.number_input("Beer Servings", min_value=0, max_value=500, value=100)

with col2:
    spirit_input = st.number_input("Spirit Servings", min_value=0, max_value=500, value=50)
    wine_input = st.number_input("Wine Servings", min_value=0, max_value=500, value=25)

# Button to predict
if st.button("Predict Consumption"):
    # Create the input DataFrame with exact column names
    input_data = pd.DataFrame({
        'country': [country_input],
        'beer_servings': [beer_input],
        'spirit_servings': [spirit_input],
        'wine_servings': [wine_input]
    })

    try:
        # Perform Prediction
        prediction = model.predict(input_data)

        # Display Results
        st.divider()
        st.subheader("Result:")
        st.success(f"The predicted **Total Pure Alcohol Consumption** is: **{prediction[0]:.2f} litres** per person.")

    except Exception as e:
        st.error(f"Prediction failed: {e}")
        st.info("This is often caused by a mismatch in feature names. Ensure they match your training set.")

# Footer
st.markdown("---")
st.caption("Model loaded from `trained_model (1).joblib`")