# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-HN0HXL2cfMY_xrrFEj3s4UNIGSYsqI
"""

import streamlit as st
import pandas as pd
import joblib
import sklearn

# Check version for debugging (visible in the app)
st.sidebar.write(f"Running sklearn version: {sklearn.__version__}")

@st.cache_resource
def load_model():
    # Ensure the path matches your uploaded file exactly
    return joblib.load('trained_model (1).joblib')

try:
    model = load_model()
    st.success("Model loaded successfully!")
except AttributeError as e:
    st.error(f"Version Mismatch Error: {e}")
    st.info("The model requires scikit-learn 1.6.1. Please check your requirements.txt file.")
except Exception as e:
    st.error(f"An error occurred: {e}")