# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-01zxXYXXCG5FnIoe-FokGzMJCmfvRt
"""

import streamlit as st
import pandas as pd
import joblib

# Load the trained model
@st.cache_resource
def load_model():
    return joblib.load('trained_model.joblib')

model = load_model()

# Title and Description
st.title("Alcohol Consumption Predictor")
st.write("""
This app predicts the **Total Pure Alcohol Consumption per person** based on servings of beer, spirits, and wine.
""")

# Sidebar for user inputs
st.sidebar.header("Input Features")

# List of countries supported by the model (derived from model metadata)
countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia",
    "Australia", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belize",
    "Bolivia", "Bosnia-Herzegovina", "Botswana", "Brazil", "Bulgaria", "Burkina Faso",
    "Burundi", "Cabo Verde", "Cameroon", "Canada", "Central African Republic", "Chad",
    "Chile", "China", "Colombia", "Comoros", "Congo", "Cook Islands", "Costa Rica",
    "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "DR Congo", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
    "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "France", "Gabon",
    "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland",
    "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica",
    "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania",
    "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
    "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
    "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
    "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "Niue", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa", "San Marino",
    "Sao Tome & Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
    "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia",
    "South Africa", "South Korea", "Spain", "Sri Lanka", "St. Kitts & Nevis",
    "St. Lucia", "St. Vincent & the Grenadines", "Sudan", "Suriname", "Swaziland",
    "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand",
    "Timor-Leste", "Togo", "Tonga", "Trinidad & Tobago", "Tunisia", "Turkey",
    "Turkmenistan", "Tuvalu", "USA", "Uganda", "Ukraine", "United Arab Emirates",
    "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam",
    "Yemen", "Zambia", "Zimbabwe"
]

def user_input_features():
    country = st.sidebar.selectbox("Country", countries)
    beer = st.sidebar.slider("Beer Servings", 0, 400, 100)
    spirit = st.sidebar.slider("Spirit Servings", 0, 500, 50)
    wine = st.sidebar.slider("Wine Servings", 0, 400, 20)

    data = {
        'country': country,
        'beer_servings': beer,
        'spirit_servings': spirit,
        'wine_servings': wine
    }
    return pd.DataFrame(data, index=[0])

input_df = user_input_features()

# Display input data
st.subheader("User Input Data")
st.write(input_df)

# Prediction
if st.button("Predict"):
    prediction = model.predict(input_df)
    st.subheader("Prediction Result")
    st.success(f"Estimated Total Pure Alcohol Consumption: **{prediction[0]:.2f} litres**")