# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9Tj3H0sxryMERfBzuoNuwMp7nCsDigA
"""

import streamlit as st
import pandas as pd
import joblib

# Load the model you uploaded
# The model is a Pipeline containing a ColumnTransformer and a RandomForestRegressor
@st.cache_resource
def load_model():
    return joblib.load('trained_model.joblib')

model = load_model()

# App Title
st.title("Alcohol Consumption Predictor")
st.write("Input the servings to predict total pure alcohol consumption per person.")

# Define the list of countries based on the model's training data
countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia",
    "Australia", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belize",
    "Bolivia", "Bosnia-Herzegovina", "Botswana", "Brazil", "Bulgaria", "Burkina Faso",
    "Burundi", "Cabo Verde", "Cameroon", "Canada", "Central African Republic", "Chad",
    "Chile", "China", "Colombia", "Comoros", "Congo", "Cook Islands", "Costa Rica",
    "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "DR Congo", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea",
    "Eritrea", "Estonia", "Ethiopia", "Fiji", "France", "Gabon", "Gambia", "Georgia",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "India", "Iran",
    "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan",
    "Kenya", "Kiribati", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia",
    "Libya", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives",
    "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
    "Moldova", "Myanmar", "Namibia", "Nepal", "Netherlands", "New Zealand", "Nicaragua",
    "Niger", "Nigeria", "Niue", "North Korea", "Norway", "Oman", "Pakistan", "Palau",
    "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Portugal",
    "Romania", "Russian Federation", "San Marino", "Sao Tome & Principe", "Saudi Arabia",
    "Senegal", "Serbia", "Sierra Leone", "Slovenia", "Solomon Islands", "South Korea",
    "Spain", "Sri Lanka", "St. Vincent & the Grenadines", "Sudan", "Suriname", "Swaziland",
    "Sweden", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad & Tobago",
    "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "USA", "Uganda", "Ukraine",
    "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu",
    "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
]

# User inputs
st.sidebar.header("Input Features")

def get_user_input():
    country = st.sidebar.selectbox("Select Country", countries)
    beer = st.sidebar.number_input("Beer Servings", min_value=0, max_value=500, value=100)
    spirit = st.sidebar.number_input("Spirit Servings", min_value=0, max_value=500, value=50)
    wine = st.sidebar.number_input("Wine Servings", min_value=0, max_value=500, value=25)

    # Create a dataframe with column names that match your model exactly
    data = {
        'country': [country],
        'beer_servings': [beer],
        'spirit_servings': [spirit],
        'wine_servings': [wine]
    }
    return pd.DataFrame(data)

input_df = get_user_input()

# Display prediction
if st.button("Predict Consumption"):
    try:
        # Use the pipeline to predict directly
        prediction = model.predict(input_df)
        st.success(f"The predicted Total Pure Alcohol Consumption is: {prediction[0]:.2f} litres")
    except Exception as e:
        st.error(f"Error during prediction: {e}")